### ISSUE TITLE
Add support for Token Lists similar to Uniswap Interface

### ISSUE THREAD

**Issue by dan13ram** [raid-guild/smart-invoice#40]
Currenty supported tokens for each network is hardcoded and users cannot choose their own tokens.

Consider referring to uniswap / honeyswap / similar codebase for implementation details.

https://user-images.githubusercontent.com/10012209/160972932-a27bbec8-cd88-4fb9-93fb-24020fa8fb99.mp4

**Comment by plor** [comment]
Estimated at $2500 (90%)

**Comment by plor** [comment]
Our implementation is not using uniswap token list standard, but we may be able to move towards something like that.
