### ISSUE TITLE
Add support for generating a PDF invoice

### ISSUE THREAD

**Issue by dan13ram** [raid-guild/smart-invoice#44]
A client or the provider should be able to generate a pdf once the invoice is completed (for tax purposes)
We may need input such as name, address, etc to generate this pdf. 
We can mark the pdf as "automatically generated".

Not sure about the legal side of this, any support and/or insight would be appreciated!

**Comment by plor** [comment]
May need to include inputs for address, phone, etc.

**Comment by plor** [comment]
Estimated at $1000 (70% confidence)
